### ISSUE TITLE
small fixes

### ISSUE THREAD

**Issue by domioedition** [ValValeria/Guzzle#1]
1) Папку vendor нужно выносить в файл .gitignore - https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md

2) "autoload": {  "psr-4": {  можно указать, как одно единственное пространство имен и указать путь к каталогу. Например 
вместо "Client\\": "src/Client", будет "ValValeria\\Guzlze\\" : "src/"  и для классов пространство имен будет **namespace ValValeria\Guzlze;**

3) По дефолту вібивает ошибку в поиске input:  _<br /><b>Notice</b>:  Undefined index: word in <b>C:\Projects_epam\Guzzle\src\URLHandler\URLHandler.php(21) : eval()'d code</b> on line <b>31</b><br />_

**Comment by ValValeria** [comment]
исправлено
